# 定义 stages（阶段，会依次执行）
stages:
  - install_deps
  - build_prod
  - deploy_prod

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/
    - dist

# 安装构建依赖
install_deps_job:
  stage: install_deps
  # 在哪个分支才会执行脚本
  only:
    # - dev
    # - release
    - main
  script:
    - echo '开始安装依赖'
    - echo `pwd`
    # - node --version
    # - npm install
   
  tags:
    - gitlab-runner-tag-1

# 构建预prod环境src目录下应用
build_prod_job:
  stage: build_prod
  only:
    - main
  script:
    - echo '开始进行打包'
    - ll -a
    # - npm run build
  tags:
    - gitlab-runner-tag-1

# 部署生产环境
deploy_prod_job:
  stage: deploy_prod
  only:
    - main
  script:
    - echo '部署生产环境阶段'
  tags:
    - gitlab-runner-tag-1

