# 定义 stages（阶段，会依次执行）
stages:
  - install_deps
  - build_prod
  - deploy_prod

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

# 安装构建依赖
install_deps_job:
  stage: install_deps
  # 在哪个分支才会执行脚本
  only:
    # - dev
    # - release
    - main
  script:
    - echo '开始安装依赖'
    - npm install
    - echo `cat ./.git/HEAD`
    - echo '获取git分支结束'
  tags:
    - docker-gitlab-runner-2

# 构建预prod环境src目录下应用
build_prod_job:
  stage: build_prod
  only:
    - main
  script:
    - echo '开始进行打包'
    - npm run build
  tags:
    - docker-gitlab-runner-2

# 部署生产环境
deploy_prod_job:
  stage: deploy_prod
  only:
    - main
  script:
    - echo `pwd`
    - echo '部署生产环境阶段'
    - echo mv build /root
  tags:
    - docker-gitlab-runner-2

